export const URLS = {
    sign_in: 'api/auth/sign-in',
    translations_list: '/api/lang/all',
    translations_edit: '/api/lang/create-edit',
    users_get_all: "/api/users/get-all",
    users_ban: "/api/users/ban",
    users_unban: "/api/users/unban",
    promo_users_list: "/api/users/get-all-promo-users",
    prize_list: "/api/prize/get-all",
    prize_add: "/api/prize/add",
    prize_edit: "/api/prize/edit",
    prize_delete: "/api/prize/delete",
    course_list: "/api/course/get-all",
    course_add: "/api/course/add",
    course_edit: "/api/course/edit",
    course_delete: "/api/course/delete",
};
